# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.31.3"
"rocks-config.nvim" = "2.0.0"

"kanagawa.nvim" = "scm"
"fzf-lua" = "0.0.1340"

tree-sitter-c = "scm"
tree-sitter-lua = "scm"
tree-sitter-markdown = "scm"
tree-sitter-vim = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-query = "scm"

tree-sitter-cpp = "scm"

[config]
colorscheme = "kanagawa"
